win32:
  start_generate: ctrl+e
  delete_cache: ctrl+d
  quit: ctrl+q
  pause: ctrl+r
darwin:
  start_generate: <ctrl>+enter
  delete_cache: <ctrl>+d
  quit: <ctrl>+q
  pause: <ctrl>+r
start_hotkey: enter
paste_hotkey: ctrl+v
send_hotkey: enter
select_all_hotkey: ctrl+a
cut_hotkey: ctrl+x
